<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Manzili.Domain\Manzili.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Admin\Services\Commands\" />
    <Folder Include="Admin\Payments\" />
    <Folder Include="Admin\Services\" />
    <Folder Include="Admin\Orders\" />
    <Folder Include="Admin\Users\" />
    <Folder Include="Admin\Services\Queries\" />
    <Folder Include="Admin\UseCases\" />
    <Folder Include="Auth\Queries\" />
    <Folder Include="Events\" />
    <Folder Include="Shared\Commands\" />
  </ItemGroup>

</Project>
