<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Manzili.Domain\Manzili.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Admin\Commands\" />
    <Folder Include="Admin\Queries\" />
    <Folder Include="Admin\UseCases\" />
    <Folder Include="Auth\Queries\" />
    <Folder Include="Events\" />
    <Folder Include="Profile\Commands\" />
    <Folder Include="Profile\Queries\" />
    <Folder Include="Profile\UseCases\" />
    <Folder Include="Seller\Commands\" />
  </ItemGroup>

</Project>
