<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Manzili.Domain\Manzili.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Buyer\Commands\Services\" />
    <Folder Include="Buyer\Commands\Users\" />
    <Folder Include="Events\" />
    <Folder Include="Admin\" />
    <Folder Include="Auth\" />
    <Folder Include="Profile\" />
    <Folder Include="Seller\" />
    <Folder Include="Buyer\UseCases\Transactions\" />
  </ItemGroup>

</Project>
